---
title: "EDA. Case Study 2 - Group 4"
author: "Keru Wu"
output: pdf_document
toc: true
number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. Load Data

```{r cars}
dat = read.csv('AB_NYC_2019.csv', na.strings = c("", "NA"))

library(purrr)
library(tidyr)
library(ggplot2)

dat %>%
  keep(is.numeric) %>% 
  gather() %>% 
  ggplot(aes(value)) +
    facet_wrap(~ key, scales = "free") +
    geom_histogram()

```


```{r}
lapply(dat, class)

```

# 2. Missing Data Manipulation

```{r}
apply(dat, 2, function(x)(sum(is.na(x))))
dat = dat[, !names(dat) %in% c('id', 'host_name','last_review')]
dat$reviews_per_month[is.na(dat$reviews_per_month)] = 0
apply(dat, 2, function(x)(sum(is.na(x))))
```

# 3. EDA plots

```{r}

library(jpeg)
library(ggpubr)
library(grid)

img = readJPEG("New_York_City_.jpg")
```


## 3.1 Neighbourhood Count

```{r}
ggplot(dat, aes(x=neighbourhood_group)) +
  geom_bar(aes(fill=neighbourhood_group))

ggplot(dat, aes(x=neighbourhood)) +
  geom_bar(aes(fill=neighbourhood), show.legend = FALSE) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size=5))
```

## 3.2 Maps
```{r}

jet.colors <- colorRampPalette(c("#00007F", "blue", "#007FFF", "cyan", "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000"))

ggplot(dat, aes(x=longitude, y = latitude, color = log(1+price)))+
  annotation_custom(rasterGrob(img, 
                               width = unit(1,"npc"), 
                               height = unit(1,"npc")), 
                    -74.258, -73.69, 40.49,40.92) + 
  geom_point(cex = 0.4) +
  scale_colour_gradientn(colors = jet.colors(7), limits = c(3,7)) 


ggplot(dat, aes(x=longitude, y = latitude, color = availability_365))+
  annotation_custom(rasterGrob(img, 
                               width = unit(1,"npc"), 
                               height = unit(1,"npc")), 
                    -74.258, -73.69, 40.49,40.92) + 
  geom_point(cex = 0.4) +
  scale_colour_gradient(low = 'red', high = 'grey') 

ggplot(dat, aes(x=longitude, y = latitude, fill = ..level.., alpha = ..level..))+
  annotation_custom(rasterGrob(img, 
                               width = unit(1,"npc"), 
                               height = unit(1,"npc")), 
                    -74.258, -73.69, 40.49,40.92) + 
  stat_density2d(geom = "polygon") + 
  scale_fill_gradient(low = "blue", high = "red") + 
  scale_alpha(range = c(0, 0.75), guide = FALSE)+
  scale_colour_gradient(low = 'red', high = 'grey') +
  


```


```{r}
ggplot(dat, aes(x=longitude, y = latitude, color = neighbourhood_group))+
  annotation_custom(rasterGrob(img, 
                               width = unit(1,"npc"), 
                               height = unit(1,"npc")), 
                    -74.258, -73.69, 40.49,40.92) + 
  geom_point(cex = 0.4) 

```

## 3.3 Neighbourhood Group

```{r}
ggplot(dat, aes(x=neighbourhood_group, y = log(1+price), fill = neighbourhood_group))+
  geom_violin() + 
  ggtitle('Neighbourhood group: price KDE')

ggplot(dat, aes(x=neighbourhood_group, y = availability_365, fill = neighbourhood_group))+
  geom_violin() + 
  ggtitle('Neighbourhood group: availability KDE')

```


```{r}
ggplot(dat, aes(x = neighbourhood_group))+
  geom_bar(aes(fill = room_type), position='dodge')+
  ggtitle("Neighbourhood group: room type")

```


## 3.4 Neighbourhood


```{r}
ggplot(dat, aes(x=neighbourhood_group, y = log(1+price), fill = neighbourhood))+
  geom_boxplot(show.legend = FALSE, outlier.size=0.2, lwd=0.2) + 
  ggtitle('Neighbourhood: price boxplot')

ggplot(dat, aes(x=neighbourhood_group, y = availability_365, fill = neighbourhood))+
  geom_boxplot(show.legend = FALSE, outlier.size=0.2, lwd=0.2) + 
  ggtitle('Neighbourhood: availability boxplot')

```


```{r}
ggplot(dat, aes(x = neighbourhood))+
  geom_bar(aes(fill = room_type), show.legend = FALSE) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size=5))+
  ggtitle("Neighbourhood: room type")

```


## 3.5 Number of Reviews
```{r}
dat1 <- dat[with(dat,order(-number_of_reviews)),]

dat1[1:10,]


```


# 4. Word Count
```{r}
Names = paste(dat$name, collapse = " ") %>% tolower()
Names = strsplit(Names, " ")[[1]]
Names = table(Names)

library(dplyr)
freq = Names %>% as.data.frame() %>% arrange(desc(Freq))

ggplot(freq[1:30,], aes(x = reorder(Names, -Freq), y = Freq))+
  geom_bar(stat = "identity", aes(fill = Names), show.legend = FALSE)+ 
  xlab("Word")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size=10))

```

# 5. Regression

## 5.0 Train Test

```{r}
dat = dat %>% mutate(id = row_number())
train = dat %>% sample_frac(.7)
test  <- anti_join(dat, train, by = 'id') 
```


```{r}

```

















 







## Spatial Data Analysis

```{r}

library(sf)
library(dplyr)
library(tidyr)


load("resultdataset 1.rdata")
adj = st_touches(p, sparse=FALSE)
adj2 = matrix(as.numeric(adj), 195, 195)
adj[adj==TRUE]=1

#corrplot::corrplot(adj,method="color",type="full",tl.col="black",cl.pos = "n")

res_dat=res_dat[res_dat$price!=0,]
res_dat=dplyr::select(as.data.frame(res_dat), -geometry)%>%
  mutate(host_id=as.factor(host_id),night=minimum_nights)
res_dat$night=cut(res_dat$night,breaks = c(0,3, 7, 14, 21,28,Inf), right = TRUE)

res_dat = res_dat %>% mutate(ind_area = as.integer(res_dat$ntaname))



dat = res_dat
dat = dat[, !names(dat) %in% c('id', 'host_name','last_review')]
dat$reviews_per_month[is.na(dat$reviews_per_month)] = 0
dat = dat %>% filter(price > 0)
dat = dat %>% filter(!is.na(dat$ind_area))

dat$nata_droped = droplevels(dat$ntaname)
dat$ind_area = as.integer(dat$nata_droped)
which(levels(dat$ntaname) %in% setdiff(levels(dat$ntaname), dat$ntaname))
# 1, 72, 135, 149
adjj = adj2[-c(1,72,135,149), -c(1,72,135,149)]


dat$availability_365 = scale(dat$availability_365)


dat$minimum_nights = as.factor(dat$minimum_nights)




dat$topic1 = grepl("apart", dat$name) | grepl("bedroom", dat$name) | grepl("studio", dat$name) | grepl("east", dat$name) | grepl("spacious", dat$name) | grepl("cozi", dat$name) | grepl("villag", dat$name) | grepl("heart", dat$name) | grepl("bright", dat$name) | grepl("west", dat$name)

dat$topic2 = grepl("brooklyn", dat$name) | grepl("williamsburg", dat$name) | grepl("beauti", dat$name) | grepl("loft", dat$name) | grepl("home", dat$name) | grepl("new", dat$name) | grepl("locat", dat$name) | grepl("great", dat$name) | grepl("brownston", dat$name) | grepl("garden", dat$name) | grepl("west", dat$name)

dat$topic3 = grepl("room", dat$name) | grepl("privat", dat$name) | grepl("park", dat$name) | grepl("near", dat$name) | grepl("cozi", dat$name) | grepl("sunni", dat$name) | grepl("bed", dat$name) | grepl("central", dat$name) | grepl("bath", dat$name) | grepl("close", dat$name) 

dat$topic4 = grepl("apt", dat$name) | grepl("bedroom", dat$name) | grepl("manhattan", dat$name) | grepl("nyc", dat$name) | grepl("luxuri", dat$name) | grepl("min", dat$name) | grepl("midtown", dat$name) | grepl("one", dat$name) | grepl("large", dat$name) | grepl("view", dat$name) 


dat = dat %>% mutate(availability_365 = ifelse(availability_365>365, 365, availability_365))

library(CARBayes)
s2 =S.CARmultilevel(formula=log(price) ~  room_type + neighbourhood_group + availability_365 + log(1 + reviews_per_month) + night +metrodist,
                family = 'gaussian', data = dat, ind.area=dat$ind_area,
                W=adjj, burnin=2000, n.sample=4000, thin = 5)

s2 =S.CARmultilevel(formula=log(price) ~ room_type + log(1+reviews_per_month) + availability_365 + minimum_nights,family = 'gaussian', data = dat, ind.area=dat$ind_area,W=adjj, burnin=500, n.sample=1000)

#s3 = S.CARmultilevel(formula = log(1+reviews_per_month) ~ room_type + log(price) + availability_365 + minimum_nights,family = 'gaussian', data = dat, ind.area=dat$ind_area,W=adjj, burnin=500, n.sample=1000)

ss = s$samples

phidf = as.data.frame(ss$phi)
colnames(phidf) = 1:191
phidf = phidf %>% gather()


Man = which(levels(dat$nata_droped) %in% unique(dat$nata_droped[dat$neighbourhood_group=="Manhattan"]))
Bky = which(levels(dat$nata_droped) %in% unique(dat$nata_droped[dat$neighbourhood_group=="Brooklyn"]))
Que = which(levels(dat$nata_droped) %in% unique(dat$nata_droped[dat$neighbourhood_group=="Queens"]))
SI = which(levels(dat$nata_droped) %in% unique(dat$nata_droped[dat$neighbourhood_group=="Staten Island"]))
Bnx = which(levels(dat$nata_droped) %in% unique(dat$nata_droped[dat$neighbourhood_group=="Bronx"]))

phidf$borough = rep('0', dim(phidf)[1])
phidf$borough[phidf$key %in% Man] = 'Manhattan'
phidf$borough[phidf$key %in% Que] = 'Queen'
phidf$borough[phidf$key %in% SI] = 'Staten Island'
phidf$borough[phidf$key %in% Bnx] = 'Bronx'
phidf$borough[phidf$key %in% Bky] = 'Brooklyn'

library(ggplot2)
ggplot(phidf, aes(x = borough, y = value, fill = key))+
  geom_boxplot(show.legend = FALSE)+
  theme(axis.text.x = element_text(hjust = 1, size=10))



ggplot(phidf, aes(x = borough, y = value, fill = key))+
  geom_boxplot(show.legend = FALSE)+
  scale_x_discrete(labels=levels(dat$nata_droped))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size=5))



```



## LDA
```{r}
Names = data.frame(name = dat$name)
library(tm)
text_corpus <- VCorpus(VectorSource(Names$name))

text_corpus_clean <- tm_map(text_corpus, content_transformer(tolower))
text_corpus_clean <- tm_map(text_corpus_clean, stemDocument)
text_corpus_clean <- tm_map(text_corpus_clean, removeNumbers)
text_corpus_clean <- tm_map(text_corpus_clean, removeWords, stopwords())
text_corpus_clean <- tm_map(text_corpus_clean, removePunctuation)
text_corpus_clean <- tm_map(text_corpus_clean, stripWhitespace)

```

```{r}
library(wordcloud)
wordcloud(text_corpus_clean, min.freq = 10, random.order = FALSE,
          colors=brewer.pal(8, "Dark2"))
```

```{r}
text_dtm <- DocumentTermMatrix(text_corpus_clean)
text_dtm

library(topicmodels)

rowTotals <- apply(text_dtm , 1, sum) #Find the sum of words in each Document
dtm.new   <- text_dtm[rowTotals> 0, ] 



```



```{r}
text_lda <- LDA(dtm.new, k = 4, method = "VEM", control = NULL)
text_lda
library(tidytext)
text_topics <- tidy(text_lda, matrix = "beta")
text_topics

library(ggplot2)
text_top_terms <- text_topics %>%
  group_by(topic) %>%
  top_n(10, beta) %>%
  ungroup() %>%
  arrange(topic, -beta)

text_top_terms %>%
  mutate(term = reorder(term, beta)) %>%
  ggplot(aes(term, beta, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  coord_flip()

```



```{r}
beta_spread <- text_topics %>%
  mutate(topic = paste0("topic", topic)) %>%
  spread(topic, beta) %>%
  filter(topic1 > .001 | topic2 > .001) %>%
  mutate(log_ratio = log2(topic2 / topic1))

beta_spread %>%
  group_by(direction = log_ratio > 0) %>%
  top_n(15, abs(log_ratio)) %>%
  ungroup() %>%
  mutate(term = reorder(term, log_ratio)) %>%
  ggplot(aes(term, log_ratio)) +
  geom_col() +
  labs(y = "Log2 ratio of beta in topic 2 / topic 1") +
  coord_flip()



```



```{r}
AB<-read.csv("AB_NYC_2019.csv") %>% 
  filter(price!=0) %>%
  mutate(reviews_per_month=replace_na(reviews_per_month,0)) %>%
  mutate(reviews_per_month=log(1+reviews_per_month),price=log(price)) 


AB_NA<-AB %>% 
  mutate(availability_365=ifelse(availability_365==0,NA,availability_365)) %>%
  mutate(availability_365=ifelse(availability_365>365,365,availability_365)) %>%
  dplyr::select(-host_id,-host_name,-id,-last_review,-name) 

modelFitInit<-lm(price ~  reviews_per_month + availability_365 +room_type+neighbourhood_group,AB_NA)
summary(modelFitInit)
AIC(modelFitInit)
```